force-app/main/default/objects/Limit__c/Limit__c.object-meta.xml
<CustomObject>
    <label>Limit</label>
    <nameField>
        <displayFormat>Limit-{0}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit__c/fields/Limit_Name__c.field-meta.xml
<CustomField>
    <fullName>Limit_Name__c</fullName>
    <label>Limit Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Limit__c/fields/Limit_Name_Ext__c.field-meta.xml
<CustomField>
    <fullName>Limit_Name_Ext__c</fullName>
    <externalId>true</externalId>
    <label>Limit Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Limit__c/fields/Limit_Type__c.field-meta.xml
<CustomField>
    <fullName>Limit_Type__c</fullName>
    <label>Limit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily Limit</fullName>
            </value>
            <value>
                <fullName>Data Limit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Limit__c/fields/Record_Date__c.field-meta.xml
<CustomField>
    <fullName>Record_Date__c</fullName>
    <label>Record Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Limit__c/fields/Remaining__c.field-meta.xml
<CustomField>
    <fullName>Remaining__c</fullName>
    <label>Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LimitsDailySyncQueueable.cls
global class LimitsDailySyncQueueable implements Queueable, Database.AllowsCallouts  {
	
    global static void execute(QueueableContext  context){
        String endpoint = URL.getOrgDomainUrl().toExternalForm() + '/services/data/v58.0/limits/';
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endpoint);
        request.setMethod('GET');
        request.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionId());
		request.setHeader('Content-Type', 'application/json');
        
        Http http = new Http();
        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
			
            Map<String, Object> limitData = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
			List<Limit__c> limitsToUpsert = new List<Limit__c>();
			List<String> limitNames = new List<String>();

            Map<String,Limit__c> existingLimitMap = new Map<String,Limit__c>();
            List<Limit__c> existingLimits = [SELECT Id,Limit_Name__c, Max__c, Remaining__c FROM Limit__c];
            
            if(!existingLimits.isEmpty()){
                for(Limit__c existinglimit : existingLimits){
                    existingLimitMap.put(existinglimit.Limit_Name__c,existinglimit);
                }
            }
            
            
            for (String limitName : limitData.keySet()) {
                Map<String, Object> values = (Map<String, Object>)limitData.get(limitName);

                Integer max = (Integer)values.get('Max');
                Integer remaining = (Integer)values.get('Remaining');
				Limit__c limitRecord;
                
                if(existingLimitMap.containsKey(limitName)){
                    limitRecord = existingLimitMap.get(limitName);
                    limitRecord.Max__c = max;
                    limitRecord.Remaining__c = remaining;
                }
                else{
                     limitRecord = new Limit__c(
                        Limit_Name__c = limitName,
                        Limit_Name_Ext__c = limitName,
                        Max__c = max,
                        Remaining__c = remaining,
                        Limit_Type__c = 'Daily Limit',
                        Record_Date__c = System.now()
                    );
                }
                limitsToUpsert.add(limitRecord);
                limitNames.add(limitName);
                
                List<Database.UpsertResult> upsertResults=Database.upsert(limitsToUpsert, Limit__c.Fields.Limit_Name_Ext__c, false);
                
                List<Id> listOfIds = new List<Id>();
                for (Integer i = 0; i < upsertResults.size(); i++) {
                    if (!upsertResults[i].success) {
                        System.debug('Failed to upsert record for ' + limitNames[i] + ': ' + upsertResults[i].getErrors()[0].getMessage());
                    }
                }
            }
            
        } else {
            System.debug('Failed to fetch limits. HTTP Status: ' + response.getStatusCode());
        }
    }
}